### ISSUE TITLE
提示词不能同步

### ISSUE THREAD

**Issue by liulsg** [thisjam/comfyui-sixgod_prompt#1]
问题：提示词不能同步，刷新界面后仍不起作用。

PromptTextArea.vue:157 Uncaught TypeError: Cannot set properties of undefined (setting 'value')
    at PromptTextArea.vue:157:19
    at index.js:18:12

**Comment by thisjam** [comment]
> 问题：提示词不能同步，刷新界面后仍不起作用。
> 
> PromptTextArea.vue:157 Uncaught TypeError: Cannot set properties of undefined (setting 'value') at PromptTextArea.vue:157:19 at index.js:18:12


更新下插件

**Comment by liulsg** [comment]
感谢，已能同步。
另外作者有没有考虑过不刷新自动同步，因为超大工作流"刷新加载"会出现所有节点重叠的错误。所以重新加载方式就会 不适合大型工作流。

**Comment by thisjam** [comment]
> 感谢，已能同步。 另外作者有没有考虑过不刷新自动同步，因为超大工作流"刷新加载"会出现所有节点重叠的错误。所以重新加载方式就会 不适合大型工作流。

如果你的工作流里面本来就有我的提示词节点，就不需要刷新，页面会在第一次加载的时候做检测。后面看看考虑加个按钮手动点击同步把。

**Comment by Gavin-Evans** [comment]
> 感谢，已能同步。 另外作者有没有考虑过不刷新自动同步，因为超大工作流"刷新加载"会出现所有节点重叠的错误。所以重新加载方式就会 不适合大型工作流。

怎么解决的？v1.75版本又不能同步了

**Comment by liulsg** [comment]
@Gavin-Evans 
1.正常安装。
2.手动添加节点，不要复制节点。
3.选好提示词后，在选择提示词界面选择同步数据。
4.如果不能同步，返回提示词选择界面再次点击点“同步数据”

**Comment by Gavin-Evans** [comment]
> @Gavin-Evans 1.正常安装。 2.手动添加节点，不要复制节点。 3.选好提示词后，在选择提示词界面选择同步数据。 4.如果不能同步，返回提示词选择界面再次点击点“同步数据”

就是通过搜索six, 手动添加的节点，还是不行啊，既无报错也无反应，感觉这个“同步数据”的功能，作者是不是忘记实现了啊，函数体中只写了个 pass, 哈哈哈

**Comment by liulsg** [comment]
@Gavin-Evans 你刷新加界面试一下。之前都是要求刷新界面的（F5）。
虽然我安装了但是我并不常用，我都是当作提示词备忘录用的（选择后复制到文本框中）。
因为我一般实现的功能复杂些，会用到多个clip文本，一个正提示词clip文本和一个负提示词clip文本根本没法满足我的需要。

**Comment by liulsg** [comment]
@Gavin-Evans 1.75版本我测试过了，可以同步。缺点只支持两个clip文本
