### ISSUE TITLE
ALT+Q快捷键呼不出来

### ISSUE THREAD

**Issue by kuku0603** [thisjam/comfyui-sixgod_prompt#3]
![image](https://github.com/thisjam/comfyui-sixgod_prompt/assets/25626867/c3fdc89f-3b26-4b29-989b-1244091ef218)

**Comment by thisjam** [comment]
> ![image](https://private-user-images.githubusercontent.com/25626867/321536323-c3fdc89f-3b26-4b29-989b-1244091ef218.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MzYyMjUsIm5iZiI6MTcxMjgzNTkyNSwicGF0aCI6Ii8yNTYyNjg2Ny8zMjE1MzYzMjMtYzNmZGM4OWYtM2IyNi00YjI5LTk4OWItMTI0NDA5MWVmMjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDExNDUyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjN2EwMzJlNWU4MmE1NzkxN2MxMzZmODU1ZDcyNGMzNDk0ZDAyMWY5MmEzMjY0NjkyNmEwYmQ0Nzg3NTZhMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EoVxrZYRovLCCFfNIQJvMM9x4W5MtQStrd29Uj8kVK4)
更新版本
