### ISSUE TITLE
提示词输入中文它还是中文

### ISSUE THREAD

**Issue by aiisoft** [thisjam/comfyui-sixgod_prompt#4]
提示词输入中文它还是中文
![Uploading 屏幕截图 2024-04-16 034820.png…]()

**Comment by thisjam** [comment]
看不见你的截图，使用教程参考：https://www.bilibili.com/video/BV11E421u7Tj/?vd_source=a393330e181e1c8aee8ca010b6cd24ca#reply217094092480
